### PR TITLE
Update visualize-node-metrics.md

### PR DESCRIPTION
**Pull request by NukeManDan**
add grafana links and fix rendering

### CODE REVIEW

**Comment by NukeManDan** [comment]
I am not able to preview the build of the img properly, @kaichaosun please do see if this works OK for you? The site's published img is tooooooo big lol

**Comment by kaichaosun** [comment]
The image failed to render in my local.
image

I haven't try this tutorial actually, and i'm confused why you change the dashboard link.

**Comment by NukeManDan** [comment]
I have fixed the issue now @kaichaosun - sorry I think Ricardo reviewed my last PR on this topic.

the tutorial had a grafana example json that was not working. I made a new one 😁 
This should be ready to merge now.

**Comment by jimmychu0807** [comment]
I want to merge your PR, but it is stuck in some CI process. Will do it in another PR #846

**Comment by jimmychu0807** [comment]
Close this as content is merged in #846

**Pull request closed without merging**
