### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by wheresaddie**
updated runtime compositional images to reflect v2.0.0 updates to FRAME

### CODE REVIEW

**Review by danforbes — CHANGES_REQUESTED** [review]
The new image is not included in this PR
image

**Comment by danforbes** [comment]
@wheresaddie can you please revert the last two commits to `master` and add the new image to this branch? Let me know if I can help with any of this.

**Comment by wheresaddie** [comment]
reverted index and adding image here as requested @danforbes .. :

substrate-frame-pallets-new


link in repo [assets dir](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/assets/substrate-frame-pallets-05.png)

**Review by riusricardo — APPROVED** [review]

**Comment by danforbes** [comment]
This PR does not specify any changes.

**Comment by riusricardo** [comment]
Right :sweat_smile: I thought that @wheresaddie planned to add the image. But you are right, it is only a comment :facepalm:

**Comment by wheresaddie** [comment]
ah i misunderstood @danforbes that you wanted the image on this literal pull and couldn't figure out what the logic was to your request :facepalm:  :woman_facepalming: I will see myself out now and _fix the actual_ branch now @riusricardo

**Comment by wheresaddie** [comment]
ahhhhh i misunderstood @danforbes that you wanted the image on this literal pull and couldn't figure out what the logic was to your ask, but was just rolling with it... facepalm woman_facepalming 

I will see myself out now and fix/update the actual branch now @riusricardo

this is such a blonde moment on my part, I cannot :P

**Comment by danforbes** [comment]
LOL no worries @wheresaddie no one was born knowing how to use git :joy: Please let me know if there's anything I can do to help you get over the learning curve :nerd_face: Also, I do not think this PR is really correct because the diagram is referring to the _Assets_ pallet, which is still part of Substrate https://substrate.dev/rustdocs/v2.0.0/pallet_assets/index.html. It was _Generic Assets_ that was removed.

**Comment by wheresaddie** [comment]
> LOL no worries @wheresaddie no one was born knowing how to use git  Please let me know if there's anything I can do to help you get over the learning curve  Also, I do not think this PR is really correct because the diagram is referring to the _Assets_ pallet, which is still part of Substrate https://substrate.dev/rustdocs/v2.0.0/pallet_assets/index.html. It was _Generic Assets_ that was removed.

good catch- i asked design to remove generic assets but i see they removed assets.. closing this PR, going to update this with design dept and trying again later

**Pull request closed without merging**
