### PR TITLE
Update to Node Template v2.0.0-rc6+1

### PR DESCRIPTION
**Pull request by danforbes**
Backport substrate-developer-hub/substrate-node-template#81

### CODE REVIEW

**Review by JoshOrndorff — APPROVED** [review]
Was that really the only place we referenced the tag?

**Comment by danforbes** [comment]
> Was that really the only place we referenced the tag?

We could go crazy and change it everywhere (e.g. https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/tutorials/build-a-dapp/prepare.md) but that didn't seem necessary? Do you disagree?

**Comment by danforbes** [comment]
FYI, this is how I checked for what to change
```shell
substrate.dev: grep -r 'git clone -b v2.0.0-rc6' ./docs
./docs/tutorials/create-a-pallet.md:git clone -b v2.0.0-rc6 https://github.com/substrate-developer-hub/substrate-pallet-template test-pallet
./docs/tutorials/create-your-first-substrate-chain/setup.md:    git clone -b v2.0.0-rc6+1 --depth 1 https://github.com/substrate-developer-hub/substrate-node-template
./docs/tutorials/create-your-first-substrate-chain/setup.md:git clone -b v2.0.0-rc6 --depth 1 https://github.com/substrate-developer-hub/substrate-front-end-template
```

**Review by wheresaddie — APPROVED** [review]

**Comment by wheresaddie** [comment]
thanks @danforbes

**Comment by JoshOrndorff** [comment]
Build a dApp tutorial: You should already have version v2.0.0-rc6 from the first chain tutorial

User: Wait, what? I just did the first chain tutorial and I have version v2.0.0-rc6+1. Are they the same?


That would be my only concern, but it isn't that big of a concern. I'm fine not updating it everywhere. Already approved.

**Comment by danforbes** [comment]
Updated per your suggestion, @JoshOrndorff...great point.

**Pull request merged**
