### PR TITLE
add pchain project

### PR DESCRIPTION
**Pull request by jefferyfengcao**
we'd like to build a parachain with pchain which is the 1st native multichain to support EVM

### CODE REVIEW

**Comment by jefferyfengcao** [comment]
logo3
plz grant the image uploading of pchain logo

**Comment by shawntabrizi** [comment]
@jefferyfengcao do you have a Substrate-based repository we can look at?

**Comment by jefferyfengcao** [comment]
Not yet. We are about to build this parachain.  pchain is already alive. And we plan to build a child chain of pchain which will be a parachain of polkadot.

**Comment by shawntabrizi** [comment]
@jefferyfengcao I think it makes sense to wait here until you actually start building :)

Often people will click on a project name and look for the project you are building.

**Comment by jefferyfengcao** [comment]
sure. we will start a substrate-based repository

**Comment by shawntabrizi** [comment]
Feel free to reopen when appropriate

**Pull request closed without merging**
