### PR TITLE
Security file update

### PR DESCRIPTION
**Pull request by imadarai**
Activating Polkadot Decoded ad 
+ Adding security files as directed by Security Team.

### CODE REVIEW

**Review by NukeManDan — APPROVED** [review]
LGTM - I am curious: what is the plan to remove this once the event is over? Just set a reminder as a new PR without the ad? (leaving the security note)

**Comment by imadarai** [comment]
@NukeManDan There is a reminder set on Web Board for  April 4th and we'll switch it to registration link, instead of vote.  Happy to set a PR as well, if thats necessary.

**Comment by NukeManDan** [comment]
got #940 set for this, the event is on may 20-21 yes?

**Comment by imadarai** [comment]
@NukeManDan Yes.  But the voting ends on 4th and then I'm told that we'll be changing the message again.

**Pull request merged**
