### PR TITLE
add gossip

### PR DESCRIPTION
**Pull request by NukeManDan**
assuming gossipsub is used over other pubsub methods (not sure)

- [ ] Are the audience and objective of the document clear? E.g. a document for developers that should teach them about transaction fees.
- [ ] Is the writing:
  - [ ] Clear: No jargon.
  - [ ] Precise: No ambiguous meanings.
  - [ ] Concise: Free of superfluous detail.
- [ ] Does it follow our style guide?
- [ ] If this is a new page, does the PR include the appropriate infrastructure, e.g. adding the page to a sidebar?
- [ ] Build the page ($ cd website && yarn start). Does it render properly? E.g. no funny lists or formatting.
- [ ] Do links go to rustdocs or devhub articles rather than code?
- [ ] If this PR addresses an issue in the queue, have you referenced it in the description?

### CODE REVIEW

**Comment by NukeManDan** [comment]
If you agree / this is correct wording, I would add links to this in the tutorials where gossip is referenced 😁

**Review by riusricardo — COMMENTED** [review]
I think this no longer stands. We use a protocol that has some similarities to GossipSub but it doesn't has the same spec. https://github.com/paritytech/substrate/tree/master/client/network-gossip
This issue explains a little bit more about the actual approach. https://github.com/paritytech/substrate/issues/6335

**Comment by wheresaddie** [comment]
thanks @riusricardo that was my guess also but I wasn't 100%, thanks for confirming

**Comment by wheresaddie** [comment]
going to close this now @NukeManDan but feel free to reopen if you have further discoveries or confirmations. Thanks for all your PRs!

**Comment by NukeManDan** [comment]
@wheresaddie I think we should address this before closing, and/or make this PR iterative until we define and properly inform people on the docs - @riusricardo what language would you suggest for use here, as "gossip" as a term appears a lot in the docs without a definition or reference to your links.

**Comment by riusricardo** [comment]
@NukeManDan I'm not saying that **gossip** is incorrect. My point is that it isn't **gossipsub**.

As @wheresaddie said, please feel free to open it again. Sorry if you felt it as a harsh response, that wasn't the intention.
I agree that we should iterate the content, unfortunately we don't have any docs that specify the protocol since it isn't following any standard and changes depending on Polkadot's development needs.

I would suggest to do a generic description of the gossip protocol without referencing gossipsub. The part of libp2p is correct.

**Comment by danforbes** [comment]
I actually asked about this term in particular when I was reworking the glossary. I believe that @joepetrowski mentioned that we tend to use it in a "general peer-to-peer networking" sense. We could potentially link out to the Wikipedia article, for instance https://en.wikipedia.org/wiki/Gossip_protocol

**Pull request closed without merging**
