### PR TITLE
Fix link

### PR DESCRIPTION
**Pull request by sacha-l**
Fixed issue with w3f link.

### CODE REVIEW

**Comment by NukeManDan** [comment]
Still broken. I think the page is throwing a 404 header incorrectly?

**Comment by sacha-l** [comment]
> Still broken. I think the page is throwing a 404 header incorrectly?

Weird! I thought I got it this time. Can you give it a try?

**Review by shawntabrizi — APPROVED** [review]
working for me

**Comment by NukeManDan** [comment]
The link is fine, the ci link checker is failing for some reason. With a 404 for the link

**Comment by jimmychu0807** [comment]
There is another link at the Reference section at the bottom of the article referring to the non-existing page.

**Pull request merged**
