### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by wheresaddie**
reworked context and topics which create questions w/o answering them

- [ ] Are the audience and objective of the document clear? E.g. a document for developers that should teach them about transaction fees.
- [ ] Is the writing:
  - [ ] Clear: No jargon.
  - [ ] Precise: No ambiguous meanings.
  - [ ] Concise: Free of superfluous detail.
- [ ] Does it follow our style guide?
- [ ] If this is a new page, does the PR include the appropriate infrastructure, e.g. adding the page to a sidebar?
- [ ] Build the page ($ cd website && yarn start). Does it render properly? E.g. no funny lists or formatting.
- [ ] Do links go to rustdocs or devhub articles rather than code?
- [ ] If this PR addresses an issue in the queue, have you referenced it in the description?

### CODE REVIEW

**Comment by danforbes** [comment]
@wheresaddie - I did not see this until _after_ I merged #634...mea culpa. We can discuss this in our meeting today.

**Comment by wheresaddie** [comment]
no worries. . :)

**Comment by danforbes** [comment]
I created this branch to preserve your changes https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/compare/df-home-update

**Comment by wheresaddie** [comment]
meh .. mi casa su casa :+1:

**Pull request closed without merging**
