### PR TITLE
KB Upgrades for v3.0.0

### PR DESCRIPTION
**Pull request by danforbes**
How should we handle the changes to the maximum block weight stuff?

### CODE REVIEW

**Comment by shawntabrizi** [comment]
There are pretty good docs already on all the new "limits" stuff here: https://crates.parity.io/frame_system/limits/index.html

Just pointing a user there and giving explicit examples of what we use in tests / production runtime should be enough.

**Review by sacha-l — DISMISSED** [review]
I found some instances where the Rust doc URLs are broken. I'm assuming its because we haven't yet made changes to the paths to reflect the new v3.0.0 changes - i.e., v2.0.0 used to be ``https://substrate.dev/rustdocs/v2.0.0/frame_system/struct.{..}/`` and for v3.0.0 we now have ``https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/struct.{..}/``.

Here's the list of broken URLs I found:
- in ``learn-substrate/weight.md`` line 111: ``MaximumBlockLength`` should be: https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/trait.Config.html#associatedtype.BlockLength (and probably renamed ``BlockLength``) and on line 113 ``MaximumBlockWeights`` should be: https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/trait.Config.html#associatedtype.BlockWeights (and renamed ``BlockWeights``)
- ``AvailableBlockRatio`` should probably live [here](https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/trait.Config.html#associatedtype) and doesn't seem to have a v3.0.0 equivalent. It also occurs 4 times.
- ``set_code`` should be https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/enum.Call.html#variant.set_code
- in ``glossary.md`` line 277: "..the Balances pallet will use **a FRAME System API**.." should link to https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/struct.Pallet.html#method.dec_consumers and at line 279 the link should either be dropped (``allow_death`` is depreciated) or link to https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/struct.Pallet.html#method.is_provider_required 
- in ``weight.md`` line 84:  link to "System pallet" should be: https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/struct.Pallet.html
- in ``events.md`` line 86: "deposit_event" should link to https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/struct.Pallet.html#method.deposit_event
- in ``metadata.md``, line 488: "..the ``InvalidSpecName`` error" should link to: https://substrate.dev/rustdocs/v3.0.0/frame_system/pallet/enum.Error.html#variant.InvalidSpecName
- in ``origin.md`` line 74: "...docs for the ``RawOrigin`` enum.." should link to https://substrate.dev/rustdocs/v3.0.0/frame_system/enum.RawOrigin.html

Hope this helps!

**Comment by jimmychu0807** [comment]
Indeed, thanks @sacha-l . I wonder why this passes our CI link-check... 

I will write a mini script to regex check these links and update them.

**Comment by jimmychu0807** [comment]
@danforbes @NukeManDan I am merging this PR for now. This is by no means the knowledgebase and tutorials are update-to-date to v3.0.0. What I have added, in addition to what Dan Forbes has done, fixing all external links to be valid URLs, and converting all `v2.0.0` string to `v3.0.0`.

Along the way, I wrote [this command line tool](https://github.com/jimmychu0807/devhub-util-scripts#cmd-find-exe) to do the link checking and regex replacement. See if you are interested in it and want to test it out yourself. As @sacha-l points out, it seems some invalid links are not verified by our link-check CI process. We should take a look into that as well.

**Review by jimmychu0807 — APPROVED** [review]

**Pull request merged**
