### PR TITLE
Add more docs about working with Rust nightlies

### PR DESCRIPTION
**Pull request by danforbes**
Depends on https://github.com/substrate-developer-hub/substrate-node-template/pull/92

### CODE REVIEW

**Comment by wheresaddie** [comment]
I can add something to KB unless perhaps this needs to live with the install @danforbes

**Review by bkchr — APPROVED** [review]
TY! :)

**Comment by riusricardo** [comment]
Good call :+1:

**Comment by wheresaddie** [comment]
thanks all!

**Pull request merged**
