### PR TITLE
Update metadata.md

### PR DESCRIPTION
**Pull request by wheresaddie**
updated to 0x0c

### CODE REVIEW

**Comment by danforbes** [comment]
Apparently this is the actual change to the transaction encoding (?) that caused the version bump https://github.com/paritytech/substrate/pull/6969 I'm not sure if this change has been incorporated into our docs.

**Comment by wheresaddie** [comment]
good to know. In that case might run this by @folsen or @gnunicorn ..?

**Comment by gnunicorn** [comment]
@thiolliere should be able to say.

**Comment by thiolliere** [comment]
below in the doc is explained each field of module metadata: name, storage, error, ... but not index.

An explanation is that index is:

index comes from how pallet is defined in construct_runtime. For example:
```
construct_runtime!(
...
{
Pallet: my_pallet::{...}, // index is implicitly 0
MySecondPallet: my_second_pallet::{..} = 2, // index is explicitly 2
MyOtherPallet: my_other_pallet::{..}, // index is implicitly 3 (same rules as rust fieldless enum 
}
)
```

I'm not sure it is interesting to go into such details, just saying it is the index assigned in construct_runtime seems enough.

About the change to the transaction encoding, this document doesn't explain it here, but maybe another document covers it ?

The encoding change is this: before:
```
construct_runtime!(
...
{
Pallet: my_pallet::{Event}, // the variant for Pallet event in the runtime event is at index 0
MySecondPallet: my_second_pallet::{Call}, // the variant for MySecondPallet call in the runtime call is at index 0
MyOtherPallet: my_other_pallet::{Call, Event}, // the variant for MyOtherPallet call in the runtime call is at index 1 and event at index 1
}
)
```
and now
```
construct_runtime!(
...
{
Pallet: my_pallet::{Event}, // the variant for Pallet event in the runtime event is at index 0
MySecondPallet: my_second_pallet::{Call}, // the variant for MySecondPallet call in the runtime call is at index 1
MyOtherPallet: my_other_pallet::{Call, Event}, // the variant for MyOtherPallet call in the runtime call is at index 2 and event at index 2
}
)
```
i.e. for Event, Call and Origin the index for the corresponding variant is the index of the pallet.

**Comment by danforbes** [comment]
Is this still relevant or was it superseded by https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/718?

**Pull request closed without merging**
