### PR TITLE
Node version 2.0.0 is crashing, updating to 2.0.1

### PR DESCRIPTION
**Pull request by henry-hz**
- [ ] Are the audience and objective of the document clear? E.g. a document for developers that should teach them about transaction fees.
- [ ] Is the writing:
  - [ ] Clear: No jargon.
  - [ ] Precise: No ambiguous meanings.
  - [ ] Concise: Free of superfluous detail.
- [ ] Does it follow our style guide?
- [ ] If this is a new page, does the PR include the appropriate infrastructure, e.g. adding the page to a sidebar?
- [ ] Build the page ($ cd website && yarn start). Does it render properly? E.g. no funny lists or formatting.
- [ ] Do links go to rustdocs or devhub articles rather than code?
- [ ] If this PR addresses an issue in the queue, have you referenced it in the description?

### CODE REVIEW

**Review by knowerlittle — APPROVED** [review]
This solved my issue!

**Comment by tansaku** [comment]
I put in a similar PR a couple of days back https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/830/files

**Comment by tansaku** [comment]
@JoshOrndorff @shawntabrizi @danforbes @wheresaddie @NukeManDan - who's in charge of ensuring that PRs to fix the documentation get merged in?  We seem to have quite a few backing up here ...

**Comment by jimmychu0807** [comment]
A similar PR #830 has been merged

**Pull request closed without merging**
