### PR TITLE
Update Home Page

### PR DESCRIPTION
**Pull request by shawntabrizi**
* Reduces padding on hero section
* Changes the call to actions to become "who" page:
    * Contract
    * Runtime
    * Front-end
* Updates getting started link to the "substrate install" page

image

### CODE REVIEW

**Comment by shawntabrizi** [comment]
Need to update the names of the buttons. Can't be "Get Started", and then three "Start Here".

**Comment by meheszsofi** [comment]
do we need the "get started" button on the top at all? without it there are 3 very straightforward paths of navigation from the homepage. 
because it is on the top banner in the middle now the "get started" button is the strongest in the hierarchy, if we want people to rather choose between 3 others (runtime/frontend/smart contract) it might make sense to simply get rid of it (or maybe rename it and put it in a less central position)

**Comment by shawntabrizi** [comment]
@meheszsofi we probably don't, can update.

**Comment by shawntabrizi** [comment]
image

Updated

**Pull request merged**
