### PR TITLE
[WIP] Runtime Migration Tutorial

### LINKED ISSUE #766: [New Tutorial] Advanced Runtime Upgrade + Storage Migration
Create a new tutorial or add a new section to the existing tutorial on runtime upgrades. The new material should demonstrate the details of storage migrations as well as strategies for testing them.

Relates to #580 and #750.

### PR DESCRIPTION
**Pull request by apopiak**
First draft for a runtime migration tutorial.

This is kind of blocked by the availability of https://github.com/paritytech/substrate/pull/7208 and https://github.com/paritytech/substrate/pull/7451 in a released Substrate version as I would like to use the pallet version as a storage guard.

aims to resolve #766 

----------------------------------------------------------

- [ ] Are the audience and objective of the document clear? E.g. a document for developers that should teach them about transaction fees.
- [ ] Is the writing:
  - [ ] Clear: No jargon.
  - [ ] Precise: No ambiguous meanings.
  - [ ] Concise: Free of superfluous detail.
- [ ] Does it follow our style guide?
- [ ] If this is a new page, does the PR include the appropriate infrastructure, e.g. adding the page to a sidebar?
- [ ] Build the page ($ cd website && yarn start). Does it render properly? E.g. no funny lists or formatting.
- [ ] Do links go to rustdocs or devhub articles rather than code?
- [ ] If this PR addresses an issue in the queue, have you referenced it in the description?

### CODE REVIEW

**Comment by apopiak** [comment]
working on code here:
https://github.com/substrate-developer-hub/substrate-node-template/tree/apopiak-migration-tutorial

**Comment by apopiak** [comment]
Dan working on code here: https://github.com/danforbes/substrate-node-template/tree/df/tut/adv-upgrade

**Comment by JoshOrndorff** [comment]
FYI, this is (a cleaned up version of) the runtime migration code I presented in seminar.

code: https://github.com/JoshOrndorff/recipes/tree/joshy-migration-station
seminar recording: https://www.youtube.com/watch?v=0eNGZpNkJk4&list=PLp0_ueXY_enXRfoaW7sTudeQH10yDvFOS

**Comment by apopiak** [comment]
Current plan (as I understand it) is to have a combination of knowledge base, recipes and the repo you mention and not have a migration tutorial. @sacha-l Feel free to weigh in with plans :-)

**Pull request closed without merging**
