### PR TITLE
update links, bump version numbers to v3 in tuto cards

### PR DESCRIPTION
**Pull request by NukeManDan**
- fix #911 CI links 
- Bump v3 for all cards 
- card images and sorting updated

### CODE REVIEW

**Comment by NukeManDan** [comment]
CI like this one - @riusricardo this should be ready to merge and it will deploy the updates 🤞🏼

**Review by riusricardo — APPROVED** [review]
👍

**Comment by riusricardo** [comment]
We should not bump all versions of tutorials in one PR. It should be done on the same PR that updates the tutorial.
Right now it says that the permission network is on v3.0 and this is not the case. Same for the private network tutorial that still has an open PR to update it.
cc: @sacha-l (just mentioning you here to keep you on the loop)

**Comment by NukeManDan** [comment]
My mistake, I should have mentioned this in the PR 🤦🏼 
Happy to have a new PR to get the right version numbers, I figured the cards would be ok to jump the gun on as we are moving fast to get them there 🚀 

LMK, as all v3 tagged issues could have the requirement instead to make sure you bump the versions correctly.
This could be in the README as a note and/or scripts helpers to remind or automatically get this correct?

**Comment by sacha-l** [comment]
> We should not bump all versions of tutorials in one PR. It should be done on the same PR that updates the tutorial.
> Right now it says that the permission network is on v3.0 and this is not the case. Same for the private network tutorial that still has an open PR to update it.
> cc: @sacha-l (just mentioning you here to keep you on the loop)

@jimmychu0807 - also keeping you in the loop 🔍

**Pull request merged**
