### PR TITLE
Update all rustdocs links using `latest` instead of a specific version

### PR DESCRIPTION
**Pull request by jimmychu0807**
@sacha-l @NukeManDan 

close: #1054

### CODE REVIEW

**Comment by NukeManDan** [comment]
I disagree that we should point to a floating reference in docs. This leads to more headaches when (frequently) breaking changes occur. Rather I think being explicitly stating versions is best to avoid this. 

The rework of the devhub allows for versioning of docs themselves too, making this more apparent

**Comment by sacha-l** [comment]
I think this could work but how would it be future proof for when we have versioning (re @NukeManDan's point)? It's my opinion that having the URL slug with specific versions will make it more manageable and user friendly. That being said, we could keep the scheme you propose here so long as we maintain previous numbered versions correspond to those same versions in our docs.

**Comment by jimmychu0807** [comment]
@NukeManDan @sacha-l 

Currently in the [rustdocs repo](https://github.com/substrate-developer-hub/rustdocs), there are `v3.0.0-monthly-2021-07` dir and `latest`, which is a linux symbolic link pointing to `v3.0.0-monthly-2021-07` dir. With the given folder structure and symlink, you can access:

- https://substrate.dev/rustdoc/v3.0.0 (the oldest version)
- https://substrate.dev/rustdoc/v3.0.0-monthly-2021-05 (2nd oldest version)
- https://substrate.dev/rustdoc/v3.0.0-monthly-2021-07 (latest version)
- https://substrate.dev/rustdoc/latest (pointing to the same docs as `v3.0.0-monthly-2021-07`, because it is symlink'ed in the underlying file system).

What I'm suggesting is we still have the exact monthly version, but we also have the `latest` symlink pointing to the latest monthly release. In future when we update the monthly release, we can just move the `latest` symlink in the rustdocs repo, and all our rustdocs links in various docs will automatically point to the latest links without needing to manually update them.

If there are breaking changes in the underlying code and rustdoc link (change to a totally new address), we are going to update the doc content anyway and at there we will also update the rustdoc link.

By adopting this change/system, it will make our future maintenance on rustdoc links in monthly release a lot easier.

**Comment by jimmychu0807** [comment]
Also, if we have a proper link checker CI tool setup, it will notify us if any of the rustdoc links are no longer working. 

Our current link checker in this repo is not working properly. And hopefully the one in devhub-v2, one imad working on, will have a properly working link checker.

**Pull request merged**
