### PR TITLE
Update low-level-data-format.md

### PR DESCRIPTION
**Pull request by kigawas**
Fix typo

### CODE REVIEW

**Comment by shawntabrizi** [comment]
I think it should be `0x` actually right?

`0b` means it should be a binary blob, and thus `0b02` and `0b03` is not valid.

**Comment by kigawas** [comment]
@shawntabrizi 

It's confusing to use __hex__ number like 0x03 (which is actually means 8 bits) to refer two bits 0b11.

**Comment by kigawas** [comment]
Or unify it with 0x00 0x01 0x02 0x03, but still a bit confusing from the context

**Comment by JoshOrndorff** [comment]
@shawntabrizi I agree that `0b02` does not make any sense. But that text does not appear in the PR."

The change was like `0x02` -> `0b10`

**Comment by shawntabrizi** [comment]
Sorry, I somehow read the PR wrong. You all are right

**Pull request merged**
