### PR TITLE
[setup] Updating git branch

### PR DESCRIPTION
**Pull request by arturgontijo**
Cloning the proper `v3.0.0+monthly-2021-05` branch as we do in the next tutorial [here](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/tutorials/add-a-pallet/index.md).

BTW, why don't we use `master` here?

- [ ] Are the audience and objective of the document clear? E.g. a document for developers that should teach them about transaction fees.
- [ ] Is the writing:
  - [ ] Clear: No jargon.
  - [ ] Precise: No ambiguous meanings.
  - [ ] Concise: Free of superfluous detail.
- [ ] Does it follow our style guide?
- [ ] If this is a new page, does the PR include the appropriate infrastructure, e.g. adding the page to a sidebar?
- [ ] Build the page ($ cd website && yarn start). Does it render properly? E.g. no funny lists or formatting.
- [ ] Do links go to rustdocs or devhub articles rather than code?
- [ ] If this PR addresses an issue in the queue, have you referenced it in the description?

### CODE REVIEW

**Review by NukeManDan — APPROVED** [review]
LGTM! thanks for the PR to update 🙏🏼

**Comment by NukeManDan** [comment]
We don't use `master` as this may include breaking changes from time to time. Only thing worse than an outdated tutorial is a broken one 😉

**Comment by arturgontijo** [comment]
Thanks @NukeManDan .

> We don't use `master` as this may include breaking changes from time to time. Only thing worse than an outdated tutorial is a broken one

What if we script all the Tutorials' steps into a single/multiple CI steps? If that makes sense I can start a draft.

**Comment by arturgontijo** [comment]
Thinking a bit more here, maybe this approach would be not that simple to maintain =/
We'd need to trigger a github action in the other repos that would notify this one about inconsistencies.
Will elaborate more on this though.

**Pull request merged**
