### PR TITLE
CI: build and check the book

### PR DESCRIPTION
**Pull request by TriplEight**
just an experiment
cc https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/979

### CODE REVIEW

**Comment by TriplEight** [comment]
Oh I completely forgot that `mdbook` requires a special structure, not going to re-factor it here.

**Comment by NukeManDan** [comment]
So do you intend to close this one?

**Comment by TriplEight** [comment]
not really, I'll try something else. The intent is to try `linkchecker` as a GHA action, but it checks (crawls) the already hosted site so it requires to be deployed within CI process which is kinda tricky thing for GHA.

**Comment by NukeManDan** [comment]
A link checker fix sounds awesome, but FYI we are close to archiving this repo & workflows. Will this be portable to https://github.com/substrate-developer-hub/substrate-docs/ (about to be public)?

**Comment by TriplEight** [comment]
@NukeManDan this really depends on your new structure and what are you going to use as a book builder.
Besides, if this is substrate.dev then the doc team have recently put up another doc portal: https://paritytech.github.io/. I'm guessing you don't want to double maintain the substrate docs so you might want to redirect there.

**Comment by NukeManDan** [comment]
ah so the intent is to use the `./docs` folder to render a fully _internally linked site to run the check on, right? Is there no tooling that reason about the file structure unrendered in MD? I know github itself allows navigation this way, as an example. 

Although as we are about to archive this repo in favor of the new docs site, maybe we should close this and continue [there](https://github.com/substrate-developer-hub/substrate-docs/)?

**Comment by TriplEight** [comment]
@NukeManDan yeah, please raise an issue there as soon as it's ready.

**Pull request closed without merging**
