### PR TITLE
Update construct_runtime.md

### PR DESCRIPTION
**Pull request by kigawas**
Update `ProvideInherent` impl code

### CODE REVIEW

**Comment by kigawas** [comment]
Sync with latest code at https://github.com/paritytech/substrate/blob/master/srml/timestamp/src/lib.rs

**Comment by shawntabrizi** [comment]
Thank you for your multiple contributions! Keep it up :)

**Comment by shawntabrizi** [comment]
Please also feel free to write to us ways we can make improvements to the clarity and content of the docs

**Comment by kigawas** [comment]
@shawntabrizi 

If you have time, could you have a look at #149 ?
It looks like `Log` and `RawLog` are removed....

**Pull request merged**
