### PR TITLE
Fix image

### LINKED ISSUE #909: Runtime picture have an error
https://substrate.dev/docs/en/knowledgebase/runtime/
image

one is elections, other is elections phragmen?

### PR DESCRIPTION
**Pull request by jimmychu0807**
close #909

### CODE REVIEW

**Comment by shawntabrizi** [comment]
@jimmychu0807 you lost the transparency in these photos. Probably fine overall, but not so nice when in dark mode.

**Review by NukeManDan — CHANGES_REQUESTED** [review]
The transparent background for sure would be best. Also, should we not duplicate this file in the assets? Just point to one instance of this from the multiple places it's used?

**Comment by jimmychu0807** [comment]
@NukeManDan the image has been updated to transparent background and dedup'ed.

**Review by NukeManDan — APPROVED** [review]
LGTM! Thanks @jimmychu0807

**Pull request merged**
